FROM node:14-stretch AS builder

ENV NODE_ENV="production"

ENV REACT_APP_BASE_URL="10.11.6.10:5050"

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY ./package.json ./package-lock.json ./

RUN [ "npm", "ci" ]

COPY ./ ./

RUN [ "npm", "run" ,"build" ]

FROM nginx

COPY  ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /home/node/app/build /usr/share/nginx/html
